name: Release - nightly - pact

run-name: "Release pact-5 from ${{ github.sha}}"
on:
  workflow_dispatch:
    
  schedule:
    - cron: '3 0 * * *'  # Daily at 00:03 UTC because midnight gets hectic

jobs:
  publish_nightly_release:
    runs-on: ubuntu-latest
    steps:
      - name: Update Nightly Tag
        uses: richardsimko/update-tag@v1.0.11
        with:
          tag_name: nightly
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  update_github_release:
    uses: kadena-io/pact-5/.github/workflows/release-manual.yml@master
    secrets: inherit
        
        
        
